### ISSUE TITLE
Help with Regex & Bot not updated?

### ISSUE THREAD

**Issue by Silarious** [TechnicallyCoded/Discord-AntiPhishingBot-Public#1]
I have forked this repo and added some links to the blacklist for discord, what would be the best way to go about blocking the following links and similar with regex. These are the entries I added that aren't triggered by already existing regex in the repo.
```
https://disccord.ru/
https://disccords.com
https://discorcd-apps.com
https://discorcl.org
https://discorclgift.net.ru
https://discrod-gifts.club
https://disocrd-gift.ru
https://dliscords.com
https://dlisocrd.ru
https://dlscordrglft.xyz
https://dlscrod-app.xyz
https://dlsocrd.online
```

Some of these are pretty out there and may not be worth the time to make regex for but the first link is very close to official links, none of the regex catch repeating characters for eg:
```
https://disccord.com/
https://diiscord.com/
https://discoord.com/
```

Upon further testing, some blacklisted sites included in the repo does not seem to be working on the provided bot, possibly not updated.
```
https://diiscord-app.ru/
https://dlsccord-apps.club/
https://discord-airdrop.com/
https://discord-informations.ru/
https://dlscord-app.com/
https://dlscord-nitro.link/
https://disordsnitros.gifts/
https://dlsccord-apps.club/
https://discordappnittro.com/
https://dlscorld.gift/
https://discocrd-app.net/
https://discord-app.net/
https://diiscord-app.ru/
https://www.dicordglfts.ga/
https://discord-gift.click/
https://discord-gift.ru/
https://discord-gift.net/
https://discord-gift.com/
https://dicsord-gift.com/
```
![%pn_2021_12_15_01_39_12](https://user-images.githubusercontent.com/19941378/146152469-c08db5da-7cc7-431c-af6f-f9034d1c4e55.gif)

Thank you for your time and effort and starting this project in the first place. I have been looking everywhere for a bot like this but couldn't find anything till I stumbled across your minecraft plugins and viewed what other projects you had on github.

**Comment by TechnicallyCoded** [comment]
Make sure that the bot has permissions. It needs access to viewing and deleting messages. Also, as of yesterday I started migrating the bot to a new host so I think you may have hit the wrong day haha 🙃 .
One link that's always banned is https://testinglinktomakesuretheantiphishingbotcandeletemessages.testonly/ so try that out if you want to make sure it's working without sending potentially dangerous links in a public channel.

EDIT: I have recently added an automated check system for when I reload the banned regex file. It pulls all the entries from the raw lists and performs a check against them. If some of them don't pass, it sends me an error with which tests failed. So I should know when some of the ones listed aren't caught by the bot.

**Comment by Silarious** [comment]
As you can see in the gif I provided I was using the test link before and after sending the list of links it wont delete, I manually tested the entire list and these were the times it didn't work.

Anyways my main inquiry was how to create new regex for the first list of links, I know some regex but what you got going is above my head and if I am to PR I want to include some new regex for the types of links I am often finding.

**Comment by TechnicallyCoded** [comment]
I'll take care of the links when I have a bit of time to include them in either already existing regex entries, or new ones. It does take a bit of time though so I can't do that right now.

In the meantime, the already existing banned links should now be working again. The bot is done migrating ^^ and here is the system I was talking about when it tests the links automatically. (nerd stuff lol)
![image](https://user-images.githubusercontent.com/29813490/146186570-433be392-16c0-4f16-a171-c2dea8239e7e.png)

**Comment by Silarious** [comment]
Thanks for updating it, should I submit a PR just so the blacklist is fully up to date? I added roughly 30 new links I found going though ban logs of my servers.

**Comment by TechnicallyCoded** [comment]
If you want to have your name on some of the added banned domains, you can always pull request the domains to ban into the raw list blacklist and I will slowly add them to the regex blacklist.
EDIT: answer: yes you can ^^

**Comment by Silarious** [comment]
Main & Sub issue resolved.
